contact_links:
  - name: Public Roadmap 
    url: https://wokwi.com/features
    about: Vote for your favorite features here
  - name: Wokwi Discord
    url: https://wokwi.com/discord
    about: Friendly chat with many helpful folks and normally prompt replies
